# Generated by Django 4.1.7 on 2023-03-14 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("snsapp", "0006_alter_comment_id_alter_follow_id_alter_post_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="title",
        ),
    ]
