# Generated by Django 4.1.7 on 2023-03-17 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("snsapp", "0011_likeforpost_likeforcomment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="likeforpost",
            name="target",
        ),
        migrations.RemoveField(
            model_name="likeforpost",
            name="user",
        ),
        migrations.DeleteModel(
            name="LikeForComment",
        ),
        migrations.DeleteModel(
            name="LikeForPost",
        ),
    ]
