# Generated by Django 4.1.7 on 2023-03-17 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("snsapp", "0012_remove_likeforpost_target_remove_likeforpost_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="like",
        ),
    ]
