# Generated by Django 4.1.7 on 2023-03-18 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("snsapp", "0017_comment_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="parent",
        ),
    ]
