# Generated by Django 4.1.7 on 2023-03-18 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("snsapp", "0019_comment_parent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="target",
            new_name="post",
        ),
        migrations.RenameField(
            model_name="reply",
            old_name="target",
            new_name="comment",
        ),
    ]
