# Generated by Django 4.1.7 on 2023-03-18 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("snsapp", "0020_rename_target_comment_post_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Reply",
        ),
    ]
