# Generated by Django 4.1.7 on 2023-03-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_alter_customuser_options_alter_customuser_managers_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(default="名前", max_length=255, verbose_name="名前"),
        ),
    ]
