# Generated by Django 4.1.7 on 2023-03-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customuser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="bg_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images", verbose_name="バック画像"
            ),
        ),
    ]
