# Generated by Django 4.1.7 on 2023-03-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_customuser_email_alter_customuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                blank=True, max_length=255, unique=True, verbose_name="名前"
            ),
        ),
    ]
