# Generated by Django 4.1.7 on 2023-03-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_customuser_email_alter_customuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True, max_length=255, unique=True, verbose_name="メールアドレス"
            ),
        ),
    ]
